---
- name: Ensure the container user group exists
  ansible.builtin.group:
    name: "heimdall"
    state: present
    gid: "{{ heimdall_uid_gid }}"
    system: true

- name: Ensure the container user exists
  ansible.builtin.user:
    name: "heimdall"
    state: present
    uid: "{{ heimdall_uid_gid }}"
    group: "heimdall"
    create_home: false
    system: true
    shell: "/usr/sbin/nologin"

- name: Ensure the config directories are present
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "heimdall"
    group: "heimdall"
  with_items:
    - /etc/heimdall

- name: Ensure all the service configuration files are in place
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/etc/heimdall/{{ item.dest }}"
    mode: 0600
    owner: "heimdall"
    group: "heimdall"
  with_items: "{{ heimdall_template_files }}"
  notify: Restart heimdall

- name: Define the default service Docker volumes
  ansible.builtin.set_fact:
    _heimdall_docker_volumes:
      - "/etc/heimdall:/config"

- name: Append any additional volume mounts
  ansible.builtin.set_fact:
    _heimdall_docker_volumes: "{{ _heimdall_docker_volumes | union(heimdall_additional_volumes) }}"

- name: Define the default Docker environment variables
  ansible.builtin.set_fact:
    _heimdall_environment_vars:
      PGID: "{{ heimdall_uid_gid }}"
      PUID: "{{ heimdall_uid_gid }}"

- name: Append any additional environment variables
  ansible.builtin.set_fact:
    _heimdall_environment_vars: "{{ _heimdall_environment_vars | combine(heimdall_additional_environment_variables) }}"

- name: Ensure the docker-compose template directory exists
  ansible.builtin.file:
    state: directory
    path: "/opt/ansible-docker-compose/heimdall"
    mode: 0755

- name: Ensure this service's docker-compose template is present
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/ansible-docker-compose/heimdall/docker-compose.yml
    mode: 0644

- name: Ensure the service container(s) is/are started
  docker_compose:
    project_src: /opt/ansible-docker-compose/heimdall
    pull: true
